var c;
c=file_text_open_write("controls.dat");
file_text_write_real(c,vk_shift);
file_text_writeln(c);
file_text_write_real(c,ord('X'));
file_text_writeln(c);
file_text_write_real(c,ord('1'));
file_text_writeln(c);
file_text_write_real(c,ord('2'));
file_text_writeln(c);
file_text_write_real(c,ord('3'));
file_text_writeln(c);
file_text_write_real(c,ord('4'));
file_text_writeln(c);
file_text_write_real(c,ord('5'));
file_text_writeln(c);
file_text_write_real(c,ord('6'));
file_text_writeln(c);
file_text_write_real(c,ord('7'));
file_text_writeln(c);
file_text_write_real(c,ord('8'));
file_text_writeln(c);
file_text_write_real(c,ord('9'));
file_text_writeln(c);
file_text_write_real(c,ord('0'));
file_text_writeln(c);
file_text_write_real(c,ord('Z'));
file_text_writeln(c);
file_text_write_real(c,ord('Q'));
file_text_writeln(c);
file_text_write_real(c,vk_f2);
file_text_writeln(c);
file_text_write_real(c,vk_f3);
file_text_writeln(c);
file_text_write_real(c,vk_f4);
file_text_writeln(c);
file_text_write_real(c,vk_f5);
file_text_writeln(c);
file_text_write_real(c,vk_f6);
file_text_writeln(c);
file_text_write_real(c,vk_f7);
file_text_writeln(c);
file_text_write_real(c,vk_enter);
file_text_writeln(c);
file_text_write_real(c,vk_f9);
file_text_writeln(c);
file_text_write_real(c,vk_f11);
file_text_writeln(c);
file_text_write_real(c,ord('C'));
file_text_writeln(c);
file_text_write_real(c,vk_f12);
file_text_writeln(c);
file_text_write_real(c,ord('A'));
file_text_writeln(c);
file_text_write_real(c,ord('D'));
file_text_writeln(c);
file_text_write_real(c,ord('W'));
file_text_writeln(c);
file_text_write_real(c,ord('S'));
file_text_writeln(c);
file_text_write_real(c,vk_control);
file_text_writeln(c);
file_text_write_real(c,ord('R'));
file_text_writeln(c);
file_text_write_real(c,ord('V'));
file_text_writeln(c);
file_text_write_string(c,"SHIFT");
file_text_writeln(c);
file_text_write_string(c,"X");
file_text_writeln(c);
file_text_write_string(c,"1");
file_text_writeln(c);
file_text_write_string(c,"2");
file_text_writeln(c);
file_text_write_string(c,"3");
file_text_writeln(c);
file_text_write_string(c,"4");
file_text_writeln(c);
file_text_write_string(c,"5");
file_text_writeln(c);
file_text_write_string(c,"6");
file_text_writeln(c);
file_text_write_string(c,"7");
file_text_writeln(c);
file_text_write_string(c,"8");
file_text_writeln(c);
file_text_write_string(c,"9");
file_text_writeln(c);
file_text_write_string(c,"0");
file_text_writeln(c);
file_text_write_string(c,"Z");
file_text_writeln(c);
file_text_write_string(c,"Q");
file_text_writeln(c);
file_text_write_string(c,"F2");
file_text_writeln(c);
file_text_write_string(c,"F3");
file_text_writeln(c);
file_text_write_string(c,"F4");
file_text_writeln(c);
file_text_write_string(c,"F5");
file_text_writeln(c);
file_text_write_string(c,"F6");
file_text_writeln(c);
file_text_write_string(c,"F7");
file_text_writeln(c);
file_text_write_string(c,"ENTER");
file_text_writeln(c);
file_text_write_string(c,"F9");
file_text_writeln(c);
file_text_write_string(c,"F11");
file_text_writeln(c);
file_text_write_string(c,"C");
file_text_writeln(c);
file_text_write_string(c,"F12");
file_text_writeln(c);
file_text_write_string(c,"A");
file_text_writeln(c);
file_text_write_string(c,"D");
file_text_writeln(c);
file_text_write_string(c,"W");
file_text_writeln(c);
file_text_write_string(c,"S");
file_text_writeln(c);
file_text_write_string(c,"CONTROL");
file_text_writeln(c);
file_text_write_string(c,"R");
file_text_writeln(c);
file_text_write_string(c,"V");
file_text_writeln(c);
file_text_write_string(c,"Secondary Weapon Toggle");
file_text_writeln(c);
file_text_write_string(c,"Toggle Scan Visor");
file_text_writeln(c);
file_text_write_string(c,"Power Beam");
file_text_writeln(c);
file_text_write_string(c,"Wave Beam");
file_text_writeln(c);
file_text_write_string(c,"Plasma Beam");
file_text_writeln(c);
file_text_write_string(c,"Spazer Beam");
file_text_writeln(c);
file_text_write_string(c,"Pulse Beam");
file_text_writeln(c);
file_text_write_string(c,"Ice Beam");
file_text_writeln(c);
file_text_write_string(c,"Nova Beam");
file_text_writeln(c);
file_text_write_string(c,"Dark Beam");
file_text_writeln(c);
file_text_write_string(c,"Light Beam");
file_text_writeln(c);
file_text_write_string(c,"Phazon Beam");
file_text_writeln(c);
file_text_write_string(c,"Morph Ball");
file_text_writeln(c);
file_text_write_string(c,"Lightsear");
file_text_writeln(c);
file_text_write_string(c,"Activate Varia Suit");
file_text_writeln(c);
file_text_write_string(c,"Activate Gravity Suit");
file_text_writeln(c);
file_text_write_string(c,"Activate Phazon Suit");
file_text_writeln(c);
file_text_write_string(c,"Activate Dark Suit");
file_text_writeln(c);
file_text_write_string(c,"Activate Light Suit");
file_text_writeln(c);
file_text_write_string(c,"Activate Corruption Suit");
file_text_writeln(c);
file_text_write_string(c,"Pause");
file_text_writeln(c);
file_text_write_string(c,"Take Screenshot");
file_text_writeln(c);
file_text_write_string(c,"Toggle 1.5x Zoom");
file_text_writeln(c);
file_text_write_string(c,"Toggle Mouse Lock To Screen");
file_text_writeln(c);
file_text_write_string(c,"Toggle Fullscreen");
file_text_writeln(c);
file_text_write_string(c,"Move Left");
file_text_writeln(c);
file_text_write_string(c,"Move Right");
file_text_writeln(c);
file_text_write_string(c,"Move Up");
file_text_writeln(c);
file_text_write_string(c,"Move Down");
file_text_writeln(c);
file_text_write_string(c,"Revert To Combat Visor and Prim. Weapon");
file_text_writeln(c);
file_text_write_string(c,"Activate Hypermode");
file_text_writeln(c);
file_text_write_string(c,"Toggle X-ray Visor");
file_text_close(c);
//FileEncrypt("controls.dat");
